project:
  type: website

website:
  title: "CUNY Tracker"
  page-navigation: true
  sidebar:
    contents:
      - href: index.qmd
        text: "About"
      - href: bytopic.qmd
        text: "List by topic"
      - text: "----"
      - href: nov-14.qmd
        text: "Nov 14"
      - href: nov-7.qmd
        text: "Nov 7"
      - text: "----"
      - href: oct-31.qmd
        text: "Oct 31"
      - href: oct-24.qmd
        text: "Oct 24"
      - href: oct-17.qmd
        text: "Oct 17"
      - href: oct-10.qmd
        text: "Oct 10"
      - href: oct-3.qmd
        text: "Oct 3"
      - text: "----"
      - href: sep-26.qmd
        text: "Sep 26"
      - href: sep-19.qmd
        text: "Sep 19"
      - href: sep-12.qmd
        text: "Sep 12"
      - href: sep-5.qmd
        text: "Sep 5"
      - text: "----"
      - href: aug-29.qmd
        text: "Aug 29"
      - href: aug-22.qmd
        text: "Aug 22"
      - href: aug-15.qmd
        text: "Aug 15"
      - href: aug-8.qmd
        text: "Aug 8"
      - href: aug-1.qmd
        text: "Aug 1"
      - text: "----"
      - href: jul-25.qmd
        text: "Jul 25"
      - href: jul-18.qmd
        text: "Jul 18"
      - href: jul-11.qmd
        text: "Jul 11"
      - href: jul-4.qmd
        text: "Jul 4"
      - text: "----"
      - href: jun-27.qmd
        text: "Jun 27"
      - href: jun-27.qmd
        text: "Jun 20"
      - href: jun-13.qmd
        text: "Jun 13"
      - href: jun-6.qmd
        text: "Jun 6"
      - text: "----"
      - href: may-30.qmd
        text: "May 30"
      - href: may-23.qmd
        text: "May 23"
      - href: may-16.qmd
        text: May 16
      - href: may-9.qmd
        text: May 9
      - text: "----"
      - href: apr-25.qmd
        text: Apr 25
      - href: apr-18.qmd
        text: Apr 18
      - href: apr-11.qmd
        text: Apr 11
      - href: apr-4.qmd
        text: Apr 4
      - text: "----"
      - href: mar-28.qmd
        text: Mar 28
      - href: mar-21.qmd
        text: Mar 21
      - href: mar-14.qmd
        text: Mar 14

format:
  html:
    theme: cosmo
    toc: true