[default.extend-words]
Pn = "Pn"
mis = "mis"
HSI = "HSI"
TRO = "TRO"
Ono = "Ono"
BA = "BA"
tryin = "tryin"
Abd = "Abd"
IFLE = "IFLE"
Coul = "Coul"
Shema = "Shema"
alls = "alls"
Cann = "Cann"
Claus = "Claus"
Nativ = "Nativ"
Stange = "Stange"
complier = "complier"
compliers = "compliers"
LSAT = "LSAT"
Wil = "Wil"
Pilar = "Pilar"